
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AutoParts
{

using System;
    using System.Collections.Generic;
    
public partial class Car
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Car()
    {

        this.AutoPart = new HashSet<AutoPart>();

    }


    public int id { get; set; }

    public int idModel { get; set; }

    public int idYear { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AutoPart> AutoPart { get; set; }

    public virtual ModelCar ModelCar { get; set; }

    public virtual YearCar YearCar { get; set; }

}

}
