
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AutoParts
{

using System;
    using System.Collections.Generic;
    
public partial class ModelCar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ModelCar()
    {

        this.Car = new HashSet<Car>();

    }


    public int id { get; set; }

    public string model { get; set; }

    public Nullable<int> idBrand { get; set; }



    public virtual BrandCar BrandCar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Car> Car { get; set; }

}

}
